using System.Xml.Serialization;

namespace AMEI;

// Generated by https://xmltocsharp.azurewebsites.net

[XmlRoot(ElementName="Description")]
public class Description {
    [XmlElement(ElementName="Title")]
    public string Title { get; set; }
    [XmlElement(ElementName="Authors")]
    public string Authors { get; set; }
    [XmlElement(ElementName="Institution")]
    public string Institution { get; set; }
    [XmlElement(ElementName="URI")]
    public string URI { get; set; }
    [XmlElement(ElementName="Reference")]
    public string Reference { get; set; }
    [XmlElement(ElementName="ExtendedDescription")]
    public string ExtendedDescription { get; set; }
    [XmlElement(ElementName="ShortDescription")]
    public string ShortDescription { get; set; }
}

[XmlRoot(ElementName="Input")]
public class Input {
    [XmlAttribute(AttributeName="name")]
    public string Name { get; set; }
    [XmlAttribute(AttributeName="description")]
    public string Description { get; set; }
    [XmlAttribute(AttributeName="inputtype")]
    public string Inputtype { get; set; }
    [XmlAttribute(AttributeName="parametercategory")]
    public string Parametercategory { get; set; }
    [XmlAttribute(AttributeName="variablecategory")]
    public string Variablecategory { get; set; }
    [XmlAttribute(AttributeName="datatype")]
    public string Datatype { get; set; }
    [XmlAttribute(AttributeName="max")]
    public string Max { get; set; }
    [XmlAttribute(AttributeName="min")]
    public string Min { get; set; }
    [XmlAttribute(AttributeName="default")]
    public string Default { get; set; }
    [XmlAttribute(AttributeName="unit")]
    public string Unit { get; set; }
}

[XmlRoot(ElementName="Inputs")]
public class Inputs {
    [XmlElement(ElementName="Input")]
    public List<Input> Input { get; set; }
}

[XmlRoot(ElementName="Output")]
public class Output {
    [XmlAttribute(AttributeName="name")]
    public string Name { get; set; }
    [XmlAttribute(AttributeName="description")]
    public string Description { get; set; }
    [XmlAttribute(AttributeName="datatype")]
    public string Datatype { get; set; }
    [XmlAttribute(AttributeName="variablecategory")]
    public string Variablecategory { get; set; }
    [XmlAttribute(AttributeName="max")]
    public string Max { get; set; }
    [XmlAttribute(AttributeName="min")]
    public string Min { get; set; }
    [XmlAttribute(AttributeName="unit")]
    public string Unit { get; set; }
}

[XmlRoot(ElementName="Outputs")]
public class Outputs {
    [XmlElement(ElementName="Output")]
    public List<Output> Output { get; set; }
}

[XmlRoot(ElementName="Initialization")]
public class Initialization {
    [XmlAttribute(AttributeName="name")]
    public string Name { get; set; }
    [XmlAttribute(AttributeName="language")]
    public string Language { get; set; }
    [XmlAttribute(AttributeName="filename")]
    public string Filename { get; set; }
}

[XmlRoot(ElementName="Function")]
public class Function {
    [XmlAttribute(AttributeName="name")]
    public string Name { get; set; }
    [XmlAttribute(AttributeName="description")]
    public string Description { get; set; }
    [XmlAttribute(AttributeName="language")]
    public string Language { get; set; }
    [XmlAttribute(AttributeName="type")]
    public string Type { get; set; }
    [XmlAttribute(AttributeName="filename")]
    public string Filename { get; set; }
}

[XmlRoot(ElementName="Algorithm")]
public class Algorithm {
    [XmlAttribute(AttributeName="language")]
    public string Language { get; set; }
    [XmlAttribute(AttributeName="platform")]
    public string Platform { get; set; }
    [XmlAttribute(AttributeName="filename")]
    public string Filename { get; set; }
}

[XmlRoot(ElementName="ModelUnit")]
public class ModelUnit {
    [XmlElement(ElementName="Description")]
    public Description Description { get; set; }
    [XmlElement(ElementName="Inputs")]
    public Inputs Inputs { get; set; }
    [XmlElement(ElementName="Outputs")]
    public Outputs Outputs { get; set; }
    [XmlElement(ElementName="Initialization")]
    public Initialization Initialization { get; set; }
    [XmlElement(ElementName="Function")]
    public List<Function> Function { get; set; } = new();
    [XmlElement(ElementName="Algorithm")]
    public Algorithm Algorithm { get; set; }
    [XmlElement(ElementName="Parametersets")]
    public string Parametersets { get; set; }
    [XmlElement(ElementName="Testsets")]
    public string Testsets { get; set; }
    [XmlAttribute(AttributeName="modelid")]
    public string Modelid { get; set; }
    [XmlAttribute(AttributeName="name")]
    public string Name { get; set; }
    [XmlAttribute(AttributeName="timestep")]
    public string Timestep { get; set; }
    [XmlAttribute(AttributeName="version")]
    public string Version { get; set; }
}
